"""empty message

Revision ID: 1304414bf600
Revises: 3b7e71e2d6b0
Create Date: 2019-07-18 01:57:58.936016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1304414bf600'
down_revision = '3b7e71e2d6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_seat_number_key', 'tickets', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tickets_seat_number_key', 'tickets', ['seat_number'])
    # ### end Alembic commands ###
